#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ShowScan.Resource", IsApplication=true)]

namespace ShowScan
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::ShowScan.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::ShowScan.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::ShowScan.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int Description1 = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int Description1Label = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int Description2 = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int Description2Label = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int Price = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int PriceLabel = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int ProductName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int ProductNameLabel = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int ScanButton = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int Stock = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int StockLabel = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int contentFrame = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int zxingscanneractivitylayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int zxingscannerfragmentlayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int error = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int success = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Scan = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
